### ISSUE TITLE
Merge Android and Python proxy.py

### ISSUE THREAD

**Issue by teiszler** [cmusatyalab/openrtist#2]
There are currently two proxies: one to support Android clients and one to support python clients. They are ostensibly identical (transformer_net.py, config.py, utils.lpy are the same) except for minute differences in the way that frames are handles by the proxy and returned. This is due to the small differences in protocol between legacy and current Gabriel clients.  We should merge these two into a single proxy which supports legacy (Android) clients via a command-line option.

**Comment by pspillai** [comment]
openvino branch now has single server.

commit d159a8c1be765b237747b5d435d7658f8eebc9ca in the openvino branch fixes python client and server to use RGB images over the network just like the android client expects.  
Once this is applied, the android server is no longer needed, since the current android client is fine with non-legacy gabriel.
